FROM registry.redhat.io/ubi9/ubi:latest@sha256:53d6c19d664f4f418ce5c823d3a33dbb562a2550ea249cf07ef10aa063ace38f as builder

USER root
WORKDIR /

RUN dnf install -y python3 python3-ruamel-yaml-clib python3-ruamel-yaml patch

RUN mkdir /licenses
COPY tempo-operator/LICENSE /licenses/.

COPY bundle-patch .
COPY tempo-operator/bundle/openshift/manifests /manifests/
COPY tempo-operator/bundle/openshift/metadata /metadata/

RUN ls /manifests -al
RUN ls /metadata -al

# stage - registry.stage.redhat.io, prod - registry.redhat.io
# set by tempo-bundle-push pipeline
ARG REGISTRY=quay.io/redhat-user-workloads

RUN ./update_bundle.sh && cat /manifests/tempo-operator.clusterserviceversion.yaml /metadata/annotations.yaml

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:cf095e5668919ba1b4ace3888107684ad9d587b1830d3eb56973e6a54f456e67
WORKDIR /

RUN mkdir /licenses
COPY tempo-operator/LICENSE /licenses/.

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=tempo-product
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.29.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/


LABEL release="0.14.1-2" \
      version="0.14.1-2" \
      com.redhat.openshift.versions=v4.12 \
      name="rhosdt/tempo-operator-bundle" \
      distribution-scope="public" \
      description="Bundle for Tempo operator" \
      io.k8s.description="Bundle for Tempo operator." \
      # TODO check if this is correct
      com.redhat.component="rhosdt" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo Operator Bundle" \
      url="https://github.com/grafana/tempo-operator" \
      vendor="Red Hat, Inc." \
      summary="Tempo operator bundle" \
      maintainer="support@redhat.com"

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY tempo-operator/bundle/openshift/tests/scorecard /tests/scorecard/

ARG USER_UID=1001
USER ${USER_UID}
