FROM registry.redhat.io/ubi9/ubi:latest@sha256:b8923f58ef6aebe2b8f543f8f6c5af15c6f9aeeef34ba332f33bf7610012de0c as install-additional-packages

WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang git && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY patches patches
COPY tempo-operator tempo-operator
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo-operator/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo-operator



RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/grafana/tempo-operator/internal/version" && \
    exportOrFail BUILD_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail OPERATOR_VERSION="0.19.0" && \
    exportOrFail COMMIT_SHA=`git rev-parse HEAD` && \
    exportOrFail TEMPO_VERSION=`cat config/manager/manager.yaml | grep -oP "docker.io/grafana/tempo:\K.*"` && \
    exportOrFail TEMPO_QUERY_VERSION=`cat config/manager/manager.yaml | grep -oP "docker.io/grafana/tempo-query:\K.*"` && \
    ls -al && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -mod=mod -tags strictfipsruntime \
      -o "tempo-operator" -trimpath -ldflags "-s -w \
                -X ${VERSION_PKG}.buildDate=${BUILD_DATE} \
                -X ${VERSION_PKG}.revision=${COMMIT_SHA} \
                -X ${VERSION_PKG}.operatorVersion=${OPERATOR_VERSION} \
                -X ${VERSION_PKG}.tempoVersion=${TEMPO_VERSION} \
                -X ${VERSION_PKG}.tempoQueryVersion=${TEMPO_QUERY_VERSION}" \
                cmd/main.go

FROM registry.redhat.io/ubi9/ubi-micro:latest@sha256:e9765516d74cafded50d8ef593331eeca2ef6eababdda118e5297898d99b7433 AS target-base

FROM registry.redhat.io/ubi9/ubi:latest@sha256:b8923f58ef6aebe2b8f543f8f6c5af15c6f9aeeef34ba332f33bf7610012de0c as install-additional-packages
COPY --from=target-base / /mnt/rootfs
RUN rpm --root /mnt/rootfs --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

RUN dnf install --installroot /mnt/rootfs --releasever 8 --setopt install_weak_deps=false --setopt reposdir=/etc/yum.repos.d --nodocs -y openssl systemd && \
    dnf clean all && \
    rm -rf /var/cache/yum
RUN rm -rf /mnt/rootfs/var/cache/*

FROM scratch
WORKDIR /
COPY --from=install-additional-packages /mnt/rootfs/ /

ARG VERSION=0.19.0-4

RUN mkdir /licenses
COPY tempo-operator/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/tempo-operator/tempo-operator /usr/bin/tempo-operator

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo-operator"]

LABEL release="${VERSION}" \
      version="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/grafana/tempo-operator" \
      com.redhat.component="tempo-operator-container" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.9::el9" \
      name="rhosdt/tempo-rhel9-operator" \
      summary="Tempo Operator" \
      description="Operator for the Tempo" \
      io.k8s.description="Operator for the Tempo." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo operator"
