FROM registry.redhat.io/ubi8/ubi:latest@sha256:312668d24dfec2e2869ab11b679728745a2745835a12aafda8e77f42aec666cb as builder

WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang git && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY tempo tempo
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail GIT_BRANCH=`git rev-parse --abbrev-ref HEAD` && \
    exportOrFail GIT_REVISION=`git rev-parse --short HEAD` && \
    exportOrFail VERSION=`git describe --tags --abbrev=0 | sed 's/^v//'` && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -C ./cmd/tempo-query -tags strictfipsruntime -mod vendor \
      -o "tempo-query" -trimpath -ldflags "-s -w -X main.Branch=${GIT_BRANCH} -X main.Revision=${GIT_REVISION} -X main.Version=${VERSION}"

FROM registry.redhat.io/ubi8/ubi-micro:latest@sha256:eae27ba458e682d6d830f6c77c9e3a4c33cf1718461397b741e674d9d37450f3 AS target-base

FROM registry.redhat.io/ubi8/ubi:latest@sha256:312668d24dfec2e2869ab11b679728745a2745835a12aafda8e77f42aec666cb as install-additional-packages
COPY --from=target-base / /mnt/rootfs
RUN rpm --root /mnt/rootfs --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

RUN dnf install --installroot /mnt/rootfs --releasever 8 --setopt install_weak_deps=false --setopt reposdir=/etc/yum.repos.d --nodocs -y openssl systemd && \
    dnf clean all && \
    rm -rf /var/cache/yum
RUN rm -rf /mnt/rootfs/var/cache/*

FROM scratch
WORKDIR /
COPY --from=install-additional-packages /mnt/rootfs/ /

RUN mkdir /licenses
COPY tempo/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/tempo/cmd/tempo-query/tempo-query /usr/bin/tempo-query

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo-query"]

LABEL release="0.16.0-1" \
      version="0.16.0-1" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/grafana/tempo-operator" \
      com.redhat.component="tempo-query-container" \
      name="rhosdt/tempo-query-rhel8" \
      summary="Tempo Query" \
      description="This container exposes a Jaeger Query compatible API from Tempo" \
      io.k8s.description="This container exposes a Jaeger Query compatible API from Tempo." \
      io.openshift.expose-services="16686:http,16687:metrics" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo Query"
