FROM registry.redhat.io/ubi8/ubi:latest@sha256:87463a8cd4ea7b3e7d066f114b64a44782515031b221253d1357d27572b6d53e as builder

WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang git && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY patches patches
COPY tempo-operator tempo-operator
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo-operator/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo-operator



RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/grafana/tempo-operator/internal/version" && \
    exportOrFail BUILD_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail OPERATOR_VERSION="0.19.0" && \
    exportOrFail COMMIT_SHA=`git rev-parse HEAD` && \
    exportOrFail TEMPO_VERSION=`cat config/manager/manager.yaml | grep -oP "docker.io/grafana/tempo:\K.*"` && \
    exportOrFail TEMPO_QUERY_VERSION=`cat config/manager/manager.yaml | grep -oP "docker.io/grafana/tempo-query:\K.*"` && \
    ls -al && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -mod=mod -tags strictfipsruntime \
      -o "tempo-operator" -trimpath -ldflags "-s -w \
                -X ${VERSION_PKG}.buildDate=${BUILD_DATE} \
                -X ${VERSION_PKG}.revision=${COMMIT_SHA} \
                -X ${VERSION_PKG}.operatorVersion=${OPERATOR_VERSION} \
                -X ${VERSION_PKG}.tempoVersion=${TEMPO_VERSION} \
                -X ${VERSION_PKG}.tempoQueryVersion=${TEMPO_QUERY_VERSION}" \
                cmd/main.go

FROM registry.redhat.io/ubi8/ubi-micro:latest@sha256:37552f11d3b39b3360f7be7c13f6a617e468f39be915cd4f8c8a8531ffc9d43d AS target-base

FROM registry.redhat.io/ubi8/ubi:latest@sha256:87463a8cd4ea7b3e7d066f114b64a44782515031b221253d1357d27572b6d53e as install-additional-packages
COPY --from=target-base / /mnt/rootfs
RUN rpm --root /mnt/rootfs --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

RUN dnf install --installroot /mnt/rootfs --releasever 8 --setopt install_weak_deps=false --setopt reposdir=/etc/yum.repos.d --nodocs -y openssl systemd && \
    dnf clean all && \
    rm -rf /var/cache/yum
RUN rm -rf /mnt/rootfs/var/cache/*

FROM scratch
WORKDIR /
COPY --from=install-additional-packages /mnt/rootfs/ /

ARG VERSION=0.19.0-3

RUN mkdir /licenses
COPY tempo-operator/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/tempo-operator/tempo-operator /usr/bin/tempo-operator

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo-operator"]

LABEL release="${VERSION}" \
      version="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/grafana/tempo-operator" \
      com.redhat.component="tempo-operator-container" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.8::el8" \
      name="rhosdt/tempo-rhel8-operator" \
      summary="Tempo Operator" \
      description="Operator for the Tempo" \
      io.k8s.description="Operator for the Tempo." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo operator"
