FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22@sha256:414352c89e06f25f79b4927328504edcdbfe676cd9596b44afff2eb4117c17e0 as builder

WORKDIR /opt/app-root/src
USER root

COPY .git .git
COPY tempo tempo
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY tempo/LICENSE /licenses/
WORKDIR /opt/app-root/src/tempo

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail GIT_BRANCH=`git rev-parse --abbrev-ref HEAD` && \
    exportOrFail GIT_REVISION=`git rev-parse --short HEAD` && \
    exportOrFail VERSION=2.6.1 && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -C ./cmd/tempo -tags strictfipsruntime -mod vendor \
      -o "tempo" -trimpath -ldflags "-s -w -X main.Branch=${GIT_BRANCH} -X main.Revision=${GIT_REVISION} -X main.Version=${VERSION}"

FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:cf095e5668919ba1b4ace3888107684ad9d587b1830d3eb56973e6a54f456e67
WORKDIR /

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install openssl -y && \
    microdnf clean all

RUN mkdir /licenses
COPY tempo/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/tempo/cmd/tempo/tempo /usr/bin/tempo

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/tempo"]

LABEL com.redhat.component="tempo-container" \
      name="rhosdt/tempo-rhel8" \
      summary="Tempo server" \
      description="Container for Tempo application" \
      io.k8s.description="Container for Tempo application." \
      io.openshift.expose-services="3100:http,4317:otlp-grpc,4318:otlp-http" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo"
