FROM registry.redhat.io/ubi8/ubi-minimal:latest@sha256:48adecc91f276734fa51987bc2203a31db9ba87a512c436c0a3fcac53135378d as builder

USER root
WORKDIR /opt/bundle-build

RUN microdnf update -y && rm -rf /var/cache/yum && \
    microdnf install -y python3 python3-pyyaml patch

RUN mkdir /licenses
COPY tempo-operator/LICENSE /licenses/.

COPY bundle-patch .
COPY tempo-operator/bundle/openshift/manifests manifests/
COPY tempo-operator/bundle/openshift/metadata metadata/

RUN ls manifests -al
RUN ls metadata -al

# stage - registry.stage.redhat.io, prod - registry.redhat.io
# set by tempo-bundle-push pipeline
ARG REGISTRY=registry.redhat.io

RUN ./update_bundle.sh && cat manifests/tempo-operator.clusterserviceversion.yaml metadata/annotations.yaml

FROM scratch
WORKDIR /

ARG VERSION=0.19.0-3

COPY tempo-operator/LICENSE /licenses/.

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=tempo-product
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.29.0
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/


LABEL release="${VERSION}" \
      version="${VERSION}" \
      com.redhat.openshift.versions=v4.12 \
      name="rhosdt/tempo-operator-bundle" \
      distribution-scope="public" \
      description="Bundle for Tempo operator" \
      io.k8s.description="Bundle for Tempo operator." \
      # TODO check if this is correct
      com.redhat.component="rhosdt" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.8::el8" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Tempo Operator Bundle" \
      url="https://github.com/grafana/tempo-operator" \
      vendor="Red Hat, Inc." \
      summary="Tempo operator bundle" \
      maintainer="support@redhat.com"

# Copy files to locations specified by labels.
COPY --from=builder /opt/bundle-build/manifests /manifests/
COPY --from=builder /opt/bundle-build/metadata /metadata/
COPY tempo-operator/bundle/openshift/tests/scorecard /tests/scorecard/

ARG USER_UID=1001
USER ${USER_UID}
