FROM registry.redhat.io/ubi9/nodejs-22:latest@sha256:47213fcf4e339356548f96af3ef7617e02a285f59ebfc5aaa82e47c70740d7c1 as builder-ui
 
WORKDIR /opt/app-root/src
USER root

COPY patches patches
COPY jaeger-ui jaeger-ui
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger-ui/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger-ui

# add deprecation notice to Jaeger UI
RUN dnf install -y patch
RUN patch -p1 < /opt/app-root/src/patches/jaegerui_deprecation_notice.patch

RUN npm ci --ignore-scripts
RUN npm run build

FROM registry.redhat.io/ubi9/ubi:latest@sha256:8bf0e8f20737e9c8a68c8a498299e9504ab397b1b1f2837acb2fef12ec698f0e as builder

WORKDIR /opt/app-root/src
USER root

RUN dnf install --nodocs -y golang git && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY .git .git
COPY jaeger jaeger
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY jaeger/LICENSE /licenses/
WORKDIR /opt/app-root/src/jaeger

COPY --from=builder-ui /opt/app-root/src/jaeger-ui /opt/app-root/src/jaeger-ui

RUN rm -rf ./cmd/query/app/ui/actual && mkdir ./cmd/query/app/ui/actual && cp -r /opt/app-root/src/jaeger-ui/packages/jaeger-ui/build/* ./cmd/query/app/ui/actual/ && find ./cmd/query/app/ui/actual -type f | xargs gzip

RUN go version && \
    exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/jaegertracing/jaeger/internal/version" && \
    exportOrFail VERSION_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'` && \
    exportOrFail GIT_LATEST_TAG="1.68.0" && \
    exportOrFail GIT_COMMIT_SHA=`git rev-parse HEAD` && \
    CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build -C ./cmd/query -mod=mod -tags strictfipsruntime,ui \
      -o ./jaeger -trimpath -ldflags "-s -w \
                -X ${VERSION_PKG}.commitSHA=${GIT_COMMIT_SHA} \
                -X ${VERSION_PKG}.latestVersion=${GIT_LATEST_TAG} \
                -X ${VERSION_PKG}.date=${VERSION_DATE}"

FROM registry.redhat.io/ubi9/ubi-micro:latest@sha256:fdf68a4f5f88cca14ae906bbec6e0fbbffe92b5b91e73e0862c961234d63b986 AS target-base

FROM registry.redhat.io/ubi9/ubi:latest@sha256:8bf0e8f20737e9c8a68c8a498299e9504ab397b1b1f2837acb2fef12ec698f0e as install-additional-packages
COPY --from=target-base / /mnt/rootfs
RUN rpm --root /mnt/rootfs --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

RUN dnf install --installroot /mnt/rootfs --releasever 9 --setopt install_weak_deps=false --setopt reposdir=/etc/yum.repos.d --nodocs -y openssl systemd && \
    dnf clean all && \
    rm -rf /var/cache/yum
RUN rm -rf /mnt/rootfs/var/cache/*

FROM scratch

ARG VERSION=0.21.0-2

WORKDIR /opt/app-root/src/
COPY --from=install-additional-packages /mnt/rootfs/ /

RUN mkdir /licenses
COPY jaeger/LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/jaeger/cmd/query/jaeger /usr/bin/jaeger

ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/jaeger"]

LABEL release="${VERSION}" \
      version="${VERSION}" \
      vendor="Red Hat, Inc." \
      distribution-scope="public" \
      url="https://github.com/grafana/tempo-operator" \
      com.redhat.component="jaeger-query-container" \
      name="rhosdt/tempo-jaeger-query-rhel9" \
      summary="Jaeger Query" \
      description="This container provides Jaeger UI for Tempo" \
      cpe="cpe:/a:redhat:openshift_distributed_tracing:3.10::el9" \
      io.k8s.description="This container provides Jaeger UI for Tempo." \
      io.openshift.expose-services="16686:uihttp" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="Jaeger Query"
