apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: tempo-icsp
spec:
  repositoryDigestMirrors:
  - source: registry.redhat.io/rhosdt/tempo-rhel9-operator
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-operator
  - source: registry.redhat.io/rhosdt/tempo-rhel9
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo
  - source: registry.redhat.io/rhosdt/tempo-query-rhel9
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-query
  - source: registry.redhat.io/rhosdt/tempo-jaeger-query-rhel9
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-jaeger-query
  - source: registry.redhat.io/rhosdt/tempo-gateway-rhel9
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-gateway
  - source: registry.redhat.io/rhosdt/tempo-gateway-opa-rhel9
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-opa
  - source: registry.redhat.io/rhosdt/tempo-operator-bundle
    mirrors:
      - quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-bundle
