apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: single-arch-build-pipeline
spec:
  tasks:
  - name: init
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:737682d073a65a486d59b2b30e3104b93edd8490e0cd5e9b4a39703e47363f0f
      - name: kind
        value: task
    params:
    - name: image-url
      value: "$(params.output-image)"
    - name: rebuild
      value: "$(params.rebuild)"
    - name: skip-checks
      value: "$(params.skip-checks)"
  - name: clone-repository
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:9709088bf3c581d4763e9804d9ee3a1f06ad6a61c23237277057c4f0cdc4f9c3
      - name: kind
        value: task
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    runAfter:
    - init
    params:
    - name: url
      value: "$(params.git-url)"
    - name: revision
      value: "$(params.revision)"
    - name: ociStorage
      value: "$(params.output-image).git"
    - name: ociArtifactExpiresAfter
      value: "$(params.image-expires-after)"
    workspaces:
    - name: basic-auth
      workspace: git-auth
  - name: prefetch-dependencies
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: prefetch-dependencies-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:153ef0382deef840d155f5146f134f39b480523a7d5c38ba9fea2b58792dd4b5
      - name: kind
        value: task
    params:
    - name: input
      value: "$(params.prefetch-input)"
    - name: hermetic
      value: "$(params.hermetic)"
    - name: dev-package-managers
      value: $(params.prefetch-dev-package-managers-enabled)
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image).prefetch
    - name: ociArtifactExpiresAfter
      value: $(params.image-expires-after)
  - name: build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: buildah-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.4@sha256:174d3c420f8c9ad4ea7a16c673ac999090d66d5df1a1da278b12d87fa105503f
      - name: kind
        value: task
    runAfter:
    - clone-repository
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    params:
    - name: IMAGE
      value: "$(params.output-image)"
    - name: DOCKERFILE
      value: "$(params.dockerfile)"
    - name: CONTEXT
      value: "$(params.path-context)"
    - name: BUILD_ARGS
      value:
      - $(params.build-args[*])
    - name: HERMETIC
      value: "$(params.hermetic)"
    - name: PREFETCH_INPUT
      value: "$(params.prefetch-input)"
    - name: IMAGE_EXPIRES_AFTER
      value: "$(params.image-expires-after)"
    - name: COMMIT_SHA
      value: "$(tasks.clone-repository.results.commit)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
  - name: build-source-image
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: source-build-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.2@sha256:9fe82c9511f282287686f918bf1a543fcef417848e7a503357e988aab2887cee
      - name: kind
        value: task
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    - input: "$(params.build-source-image)"
      operator: in
      values:
      - 'true'
    runAfter:
    - build-container
    params:
    - name: BINARY_IMAGE
      value: "$(params.output-image)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
  - name: deprecated-base-image-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:5d63b920b71192906fe4d6c4903f594e6f34c5edcff9d21714a08b5edcfbc667
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
  - name: clair-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clair-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:712afcf63f3b5a97c371d37e637efbcc9e1c7ad158872339d00adc6413cd8851
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: rpms-signature-scan
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: rpms-signature-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:7b80f5a319d4ff1817fa097cbdbb9473635562f8ea3022e64933e387d3b68715
      - name: kind
        value: task
      resolver: bundles
  - name: sast-snyk-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: sast-snyk-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.3@sha256:a1cb59ed66a7be1949c9720660efb0a006e95ef05b3f67929dd8e310e1d7baef
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: clamav-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clamav-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.2@sha256:62c835adae22e36fce6684460b39206bc16752f1a4427cdbba4ee9afdd279670
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: sast-coverity-check
    params:
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE
      value: $(params.output-image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: BUILD_ARGS
      value:
      - $(params.build-args[*])
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - coverity-availability-check
    taskRef:
      params:
      - name: name
        value: sast-coverity-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-coverity-check-oci-ta:0.2@sha256:044412899f847dad17a64ae84f43ace5fd6fb976acbe64a42eb0a06bbff92499
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
    - input: $(tasks.coverity-availability-check.results.STATUS)
      operator: in
      values:
      - success
  - name: coverity-availability-check
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: coverity-availability-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-coverity-availability-check:0.2@sha256:0b35292eed661c5e3ca307c0ba7f594d17555db2a1da567903b0b47697fa23ed
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sast-shell-check
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: sast-shell-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:a591675c72f06fb9c5b1a3d60e6e4c58e4df5f7da180c7a4691a692a6e7e6496
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sast-unicode-check
    params:
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - build-container
    taskRef:
      params:
      - name: name
        value: sast-unicode-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.1@sha256:424f2f659c02998dc3a43e1ce869e3148982c59adb74f953f8fa91ff1c9ab86e
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  params:
  - name: git-url
    type: string
    description: Source Repository URL
  - name: revision
    type: string
    description: Revision of the Source Repository
    default: ''
  - name: output-image
    type: string
    description: Fully Qualified Output Image
  - name: path-context
    type: string
    description: Path to the source code of an application's component from where to build image.
    default: "."
  - default: []
    description: Array of --build-arg values ("arg=value" strings) for buildah
    name: build-args
    type: array
  - name: dockerfile
    type: string
    description: Path to the Dockerfile inside the context specified by parameter path-context
    default: Dockerfile
  - name: rebuild
    type: string
    description: Force rebuild image
    default: 'false'
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ''
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: "false"
    description: Enable dev-package-managers in prefetch task
    name: prefetch-dev-package-managers-enabled
    type: string
  - name: java
    type: string
    description: Java build
    default: 'false'
  - name: image-expires-after
    description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
    default: ''
  - name: build-source-image
    type: string
    description: Build a source image.
    default: 'true'
  workspaces:
  - name: git-auth
    optional: true
  results:
  - name: IMAGE_URL
    description: ''
    value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: IMAGE_DIGEST
    description: ''
    value: "$(tasks.build-container.results.IMAGE_DIGEST)"
  - name: CHAINS-GIT_URL
    description: ''
    value: "$(tasks.clone-repository.results.url)"
  - name: CHAINS-GIT_COMMIT
    description: ''
    value: "$(tasks.clone-repository.results.commit)"
  finally:
  - name: show-sbom
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:04f15cbce548e1db7770eee3f155ccb2cc0140a6c371dc67e9a34d83673ea0c0
      - name: kind
        value: task
    params:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: show-summary
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:870d9a04d9784840a90b7bf6817cd0d0c4edfcda04b1ba1868cae625a3c3bfcc
      - name: kind
        value: task
    params:
    - name: pipelinerun-name
      value: "$(context.pipelineRun.name)"
    - name: git-url
      value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
    - name: image-url
      value: "$(params.output-image)"
    - name: build-task-status
      value: "$(tasks.build-container.status)"

