apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-tempo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/tempo-fbc-v4-21-pull-request.yaml".pathChanged() ||
      ".tekton/tempo-fbc-v4-21-push.yaml".pathChanged() ||
      ".tekton/fbc-build-pipeline.yaml".pathChanged() ||
      "Dockerfile-v4-21.catalog".pathChanged() ||
      "catalog/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tempo-fbc-v4-21-main
    appstudio.openshift.io/component: tempo-fbc-v4-21-main
    pipelines.appstudio.openshift.io/type: build
  name: tempo-fbc-v4-21-main-on-push
  namespace: rhosdt-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: hermetic
    value: "true"
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-fbc-v4-21:{{revision}}
  - name: dockerfile
    value: Dockerfile-v4-21.catalog
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
  pipelineRef:
    name: fbc-build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
