apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-tempo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    build.appstudio.openshift.io/build-nudge-files: "bundle-patch/bundle.env"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/tempo-operator-pull-request.yaml".pathChanged() ||
      ".tekton/tempo-operator-push.yaml".pathChanged() ||
      "Dockerfile.operator".pathChanged() ||
      "rpms.lock.yaml".pathChanged() ||
      "tempo-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tempo-main
    appstudio.openshift.io/component: tempo-operator-main
    pipelines.appstudio.openshift.io/type: build
  name: tempo-operator-main-on-push
  namespace: rhosdt-tenant
spec:
  taskRunSpecs:
  - pipelineTaskName: prefetch-dependencies
    computeResources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        memory: 4Gi
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./tempo-operator"}, {"type": "rpm"}]'
  - name: hermetic
    value: "true"
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-operator:{{revision}}
  - name: dockerfile
    value: Dockerfile.operator
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  - name: snyk-project
    value: tempo-operator
  - name: snyk-ignore-file-paths
    value: "tempo/,jaeger/,jaeger-ui/,api/,opa-openshift/"
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-tempo-operator-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
