apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-tempo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/single-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/tempo-bundle-quay-pull-request.yaml".pathChanged() ||
      ".tekton/tempo-bundle-quay-push.yaml".pathChanged() ||
      "Dockerfile.bundle".pathChanged() ||
      "bundle-patch/***".pathChanged() ||
      "tempo-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tempo
    appstudio.openshift.io/component: tempo-bundle-quay
    pipelines.appstudio.openshift.io/type: build
  name: tempo-bundle-quay-on-push
  namespace: rhosdt-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/tempo/tempo-bundle-quay:{{revision}}
  - name: dockerfile
    value: Dockerfile.bundle
  - name: path-context
    value: .
  - name: hermetic
    value: "false"
  pipelineRef:
    name: single-arch-build-pipeline
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
